platform: linux
image_resource:
  type: registry-image
  source:
    repository: concourse/oci-build-task
    tag: latest
inputs:
  - name: repo
outputs:
  - name: image
params:
  CONTEXT: repo/pipeline
run:
  path: build