platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: latest
inputs:
  - name: main
outputs:
  - name: main
run:
  path: sh
  args:
    - -exc
    - |
      cat <<EOF > main/Dockerfile
      FROM node:18
      WORKDIR /app
      COPY . .
      RUN npm install
      CMD ["npm", "start"]
      EOF
