platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine/git
    tag: latest
inputs:
  - name: main
outputs:
  - name: new-image-info
run:
  path: sh
  dir: main
  args:
    - -exc
    - |
      git rev-parse --short HEAD > ../new-image-info/git-sha