platform: linux
image_resource:
  type: registry-image
  source:
    repository: gcr.io/google.com/cloudsdktool/google-cloud-cli
    tag: 489.0.0-alpine
params:
  GOOGLE_APPLICATION_CREDENTIALS: /tmp/key.json
inputs:
  - name: updated-pipeline
run:
  path: sh
  dir: updated-pipeline
  args:
    - -exc
    - |
      printf "%s" "$GCLOUD_SERVICE_ACCOUNT" > /tmp/key.json
      gcloud auth activate-service-account --key-file=/tmp/key.json
      gcloud config set project ${GCLOUD_PROJECT}
      gsutil cp pipeline.json gs://${GCLOUD_BUCKET}/pipeline.json