resources:
  - name: main
    type: git
    icon: github
    check_every: 24h
    source:
      uri: git@github.com:Kiruthick7/concourse-learn.git
      branch: main
      private_key: ((github-private-key))

  - name: google-artifact-registry
    type: registry-image
    source:
      repository: asia-south1-docker.pkg.dev/symbolic-app-451410-m7/concourse-learn-docker
      username: _json_key
      password: ((gcp-service-key))

jobs:
  - name: pr-verify
    public: true
    plan:
      - get: main
        trigger: true
      - task: run-tests
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: 18
          inputs:
            - name: main
          run:
            path: sh
            args:
              - -exc
              - |
                cd main
                npm install
                npm run build

  - name: build-and-push-image
    plan:
      - get: main
        trigger: true
      - task: tag-pipeline
        file: main/ci/tasks/get-tag.yml
      - task: generate-dockerfile
        file: main/ci/tasks/generate-dockerfile.yml
      - task: build-image
        privileged: true
        file: main/ci/tasks/build-pipeline-image.yml
        input_mapping:
          repo: main
      - put: google-artifact-registry
        params:
          image: image/image.tar
          additional_tags: latest, $(cat new-image-info/git-sha)
